name: Destroy Pulumi Multi-Stack

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to destroy (dev, staging, prod)"
        required: true

jobs:
  destroy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Pulumi CLI
        uses: pulumi/actions@v4
        with:
          pulumi-version: 3.99.0

      - name: Pulumi Login
        run: pulumi login

      - name: Select Stack
        id: stack
        run: |
          echo "stack=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT

      - name: Pulumi Stack Select
        run: pulumi stack select ${{ steps.stack.outputs.stack }}

      - name: Pulumi Destroy
        run: pulumi destroy --yes --non-interactive
